### ISSUE TITLE
Support for nested relationship?

### ISSUE THREAD

**Issue by kumy** [gte451f/phalcon-json-api-package#58]
Does the library support nested relationship?

http://jsonapi.org/format/#fetching-relationships

> In order to request resources related to other resources, a dot-separated path for each relationship name can be specified:
```
GET /articles/1?include=comments.author HTTP/1.1
Accept: application/vnd.api+json
```

**Comment by gte451f** [comment]
This isn't supported yet.  I don't have plans to add it anytime soon, but I'll gladly accept PRs!
